name: Waka Readme

on:
  repository_dispatch:
    types: [test_trigger]
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: "True"
          SHOW_TOTAL_CODE_TIME: "True"
          SHOW_LOC_CHART: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_PROJECTS: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_COMMIT: "False"
          SHOW_LANGUAGE: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          
